### ISSUE TITLE
Filter Reset issue

### ISSUE THREAD

**Issue by ChaStPierre** [xaksis/vue-good-table#368]
### Issue Type (delete the irrelevant ones) 

- [x] Bug
 

### Specs
Version 2.12.1 introduced a bug when trying to use the reset method on a table. Issues does not exist in 2.12.

What browser?
All browsers

### Expected Behavior
What did you expect to happen?
When invoking this.$refs['sr-table'].reset(); it should reset columns filters

### Actual Behavior
What actually happened?
Using v2.12.1 and above does not find the reset method as indicated in the browser console.

> vue.js:6 TypeError: Cannot read property 'reset' of undefined
>     at a.reset (Table.vue:807)
>     at a.n [as reset] (vue.js:6)

### Steps to Reproduce the Problem
Please detail your steps here
Easily reproducible. Just change the library version number on a table which has column filters enabled with a reset button.  
1. Enter text in column filter
2. click reset button (behavior will be different based on the library version number)

**Comment by xaksis** [comment]
hey @ChaStPierre! The error seems to indicate that *the ref for the table is undefined*, not the reset method itself - meaning `this.$refs['sr-table']` doesn't exist when you're trying to reset it. You need to wait for table component to render and become part of $refs before calling reset on it. 

closing.

**Comment by ChaStPierre** [comment]
Thanks for the follow. 
Actually the ref is properly defined and the table is totally rendered. Note that changing to version 2.12.x bring out the issue/bug.

**Comment by xaksis** [comment]
@ChaStPierre apologies for closing this issue prematurely. I see this is actually a bug. Will work on it.

**Comment by xaksis** [comment]
This should now be fixed in v2.13.2

**Comment by ChaStPierre** [comment]
I've just tested the latest version and the issue still exists. I had to revert to version 2.12

Also note that your version number is not in sync.

Thanks for the quick follow-up.

**Comment by xaksis** [comment]
@ChaStPierre can you explain what you mean by version number not in sync? the currently released version is 2.13.2 
here's a jsfiddle to show you that it works: 
https://jsfiddle.net/aks9800/1bkzcd3n/

**Comment by ChaStPierre** [comment]
Downloaded v2.13.2 and opened vue-good-table.js which shoed version 2.13.1

**Comment by xaksis** [comment]
Perhaps you downloaded it before npm had a chance to sync it? Not sure. Seems fine to me though.

**Comment by ChaStPierre** [comment]
I`ve just ted using the cdn version (js shows 2.12.3) and it works perfectly! The issue resides in the latest release package pointing to v2.13.1
Thanks for the quick fix :)

**Comment by ChaStPierre** [comment]
The latest version via the release section points to 2.13.1

https://github.com/xaksis/vue-good-table/releases <https://github.com/xaksis/vue-good-table/releases>

**Comment by xaksis** [comment]
ah yeah... that's a bug in the release plugin I use... it sometimes takes the last commit of the last release. You can ignore that. The npm package/or github clone should give you the right version.
